# Neural Networks Attempt to Mimic Several Functions
#### Team Leader: Austin Derrow-Pinion
#### Team Members: Kice Sanders, Aaron Bartee

### Table of Contents
 
 * [Executive Summary](#Executive-Summary)
 * [Links](#Links)
 * [Supplement](ProjectReportSupplement.ipynb) 

### Executive Summary
In this study, we attempt to compare the power of neural networks’ ability to mimic functions with the functions themselves. The Universal Approximation Theorem states that for any continuous function, there exists a feed-forward network with only a single hidden layer that can approximate it. This is motivation for us to try out different functions and try to train a neural network to accurately approximate as many as we can. For functions that are not approximated well, we can observe the function and try to learn more about neural networks as to why it did not learn the function.

### Introduction
The overall objective is to explore the complexity of problems which are able to be solved by applying learning with neural networks. We have programmed several different functions in Python, all of which range in complexity. We can have a loop that feeds in a very large number of inputs to these functions and records the output in order to generate a large amount of data. The programs were made by us so we can generate as much data as we need to train the neural network. 

With this data, we will use supervised learning by feeding the network with the input data and using back-propagation to update the weights in the network. The neural network will be programmed using TensorFlow. We have been going through tutorials on TensorFlow to learn how to use it, but have not been able to learn how to use this kind of neural network just yet.

### Data Preparation
Since all functions are written by us, we are able to randomly generate inputs for each function and record the output. This allows us to have as much data as needed to observe the performance of the neural network.

In [24]:
import numpy as np
from trainingFunctions import *

# fill an 2D array, mapping inputs to the fib function
# to the output of the fib function
TRAINING_EXAMPLES = 10
fib_example = np.ndarray(shape=(TRAINING_EXAMPLES,2), dtype='int64')
for x in range(len(fib_example)):
    input_ = int(np.random.randint(1,70))
    fib_example[x,] = [input_, fib(input_)]
print(fib_example)

[[         11          89]
 [         54 86267571272]
 [          5           5]
 [         42   267914296]
 [         50 12586269025]
 [          1           1]
 [         34     5702887]
 [          4           3]
 [         52 32951280099]
 [         15         610]]


In [25]:
# fill an 2D array, mapping inputs to the evenParity function
# to the output of the evenParity function
TRAINING_EXAMPLES = 10
evenParity_example = np.ndarray(shape=(TRAINING_EXAMPLES,2), dtype='int64')
for x in range(len(evenParity_example)):
    input_ = int(np.random.randint(1,2000))
    evenParity_example[x,] = [input_, evenParity(input_)]
print(evenParity_example)

[[1128    0]
 [1782    0]
 [1569    0]
 [1514    1]
 [1586    1]
 [ 515    1]
 [ 908    1]
 [1861    0]
 [1057    1]
 [1584    0]]


In [32]:
# fill an 2D array, mapping inputs to the oddParity function
# to the output of the oddParity function
TRAINING_EXAMPLES = 10
oddParity_example = np.ndarray(shape=(TRAINING_EXAMPLES, 2), dtype='int64')
for x in range(len(oddParity_example)):
    input_ = int(np.random.randint(1,2000))
    oddParity_example[x,] = [input_, oddParity(input_)]
print(oddParity_example)

[[1785    1]
 [ 668    0]
 [1269    0]
 [1322    0]
 [ 416    0]
 [1031    1]
 [ 899    0]
 [ 535    0]
 [ 786    1]
 [1720    1]]


In [74]:
# Get training data for the isPalindrome function
# using a range of letters from 'a' to 'z' (97 - 122)

TRAINING_EXAMPLES = 10
readable_data = []
real_data = []
for x in range(TRAINING_EXAMPLES):
    # generate 10 training examples
    size_of_string = np.random.randint(1,50) # range can increase
    input_ = [np.random.randint(97, 122) for x in range(size_of_string)]
    if np.random.randint(1,3) == 1:
        # half the time, make it a guaranteed palindrome
        input_ = makePalindrome(input_)
    output = isPalindrome(input_)
    real_data.append([input_, output])
    input_ = "".join([chr(i) for i in input_])
    readable_data.append([input_, output])

# Manually test this palindrome. A disease that causes inflammation
# in the lungs from inhaling very fine silica dust.
input_ = makePalindrome('pneumonoultramicroscopicsilicovolcanoconiosis')
output = isPalindrome(input_)
readable_data.append([input_, output])
input_ = [ord(i) for i in input_]
real_data.append([input_, output])

print(readable_data)
print(real_data)

[['ctkevwcekusrdghgirfvtyrpsochayygtbbtgyyahcosprytvfrighgdrsukecwvektc', True], ['vitjgnullungjtiv', True], ['mhsicttaonvsikvqoegcrvgfkphqyof', False], ['n', True], ['nibtiugxhmiygjjgyimhxguitbin', True], ['ppuuaxipukkfhiqojwpncbcljbgqlnjdgymbynb', False], ['jvuoqsltbsjrvvtpcbdekwbgeucnfsfxscdrwsweilliewswrdcsxfsfncuegbwkedbcptvvrjsbtlsqouvj', True], ['lkxqh', False], ['musqcahvaxdeemefyvoxbbyjahdqatjclaixg', False], ['ynleyigtuapaguufmppwhtwdyyliilyydwthwppmfuugapautgiyelny', True], ['pneumonoultramicroscopicsilicovolcanoconiosissisoinoconaclovociliscipocsorcimartluonomuenp', True]]
[[[99, 116, 107, 101, 118, 119, 99, 101, 107, 117, 115, 114, 100, 103, 104, 103, 105, 114, 102, 118, 116, 121, 114, 112, 115, 111, 99, 104, 97, 121, 121, 103, 116, 98, 98, 116, 103, 121, 121, 97, 104, 99, 111, 115, 112, 114, 121, 116, 118, 102, 114, 105, 103, 104, 103, 100, 114, 115, 117, 107, 101, 99, 119, 118, 101, 107, 116, 99], True], [[118, 105, 116, 106, 103, 110, 117, 108, 108, 117, 110, 103, 106, 

### Links
We define several different functions we can use to train a neural network in the [ProjectReportSupplement.ipynb](ProjectReportSupplement.ipynb) notebook.

The Universal Law of Approximation is explained here: [http://neuralnetworksanddeeplearning.com/chap4.html]

Our code is open sourced on GitHub here:
[https://github.com/derrowap/MA490-MachineLearning-FinalProject/blob/master/trainingFunctions.py]